version: '3.9'

services:
  tasks-postgres:
    container_name: tasks-postgres_container
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql@14/data:rw
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=tasks_db
  pgadmin:
    container_name: pgadmin4_container
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: salouri@example.org
      PGADMIN_DEFAULT_PASSWORD: taskspass
    ports:
      - '5050:80'
